### ISSUE TITLE
Fix ContextMenus

### ISSUE THREAD

**Issue by ELanning** [WPF-Pilot/WpfPilot#16]
- ContextMenus are not opening properly.
- ContextMenu content cannot be queried properly.

Fixes are on the way for both of these problems.

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the ClickCommand class to properly open ContextMenus when right-clicking and added support for querying ContextMenu content.

I also created pull request: https://github.com/WPF-Pilot/WpfPilot/pull/17


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by ELanning** [comment]
Fixed in 1.2.5.
